import smtplib
import asyncio
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

from config import settings


def _build_html_email(form: dict) -> str:
    """Build a nicely formatted HTML email for the clinic."""
    service_row = f"<tr><td><b>Service Enquiry</b></td><td>{form.get('service', 'Not specified')}</td></tr>"
    return f"""
    <html><body style="font-family: Arial, sans-serif; color: #333;">
      <div style="max-width:600px;margin:auto;border:1px solid #ddd;border-radius:8px;overflow:hidden;">
        <div style="background:#1a6eb5;padding:20px;text-align:center;">
          <h2 style="color:white;margin:0;">🦷 New Contact Form Submission</h2>
          <p style="color:#cce4ff;margin:4px 0 0;">Ashirwad Dental Clinic</p>
        </div>
        <div style="padding:24px;">
          <p>You have received a new enquiry. Details below:</p>
          <table style="width:100%;border-collapse:collapse;">
            <tr style="background:#f4f8ff;">
              <td style="padding:10px;width:35%;"><b>Name</b></td>
              <td style="padding:10px;">{form['name']}</td>
            </tr>
            <tr>
              <td style="padding:10px;"><b>Email</b></td>
              <td style="padding:10px;"><a href="mailto:{form['email']}">{form['email']}</a></td>
            </tr>
            <tr style="background:#f4f8ff;">
              <td style="padding:10px;"><b>Phone</b></td>
              <td style="padding:10px;"><a href="tel:{form['phone']}">{form['phone']}</a></td>
            </tr>
            {service_row}
            <tr style="background:#f4f8ff;">
              <td style="padding:10px;"><b>Message</b></td>
              <td style="padding:10px;">{form['message']}</td>
            </tr>
            <tr>
              <td style="padding:10px;"><b>Received At</b></td>
              <td style="padding:10px;">{datetime.now().strftime('%d %b %Y, %I:%M %p')}</td>
            </tr>
          </table>
        </div>
        <div style="background:#f0f0f0;padding:12px;text-align:center;font-size:12px;color:#888;">
          This email was auto-generated by the Ashirwad Dental Clinic contact form.
        </div>
      </div>
    </body></html>
    """


def _send_sync(form: dict):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"New Contact Enquiry from {form['name']} – Ashirwad Dental"
    msg["From"] = settings.SMTP_SENDER
    msg["To"] = settings.CLINIC_EMAIL

    msg.attach(MIMEText(_build_html_email(form), "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(settings.SMTP_SENDER, settings.SMTP_PASSWORD)
        server.sendmail(settings.SMTP_SENDER, settings.CLINIC_EMAIL, msg.as_string())


async def send_email_notification(form: dict):
    """Non-blocking email send using a thread pool."""
    loop = asyncio.get_event_loop()
    await loop.run_in_executor(None, _send_sync, form)
